apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:  
  name: loginfunctionality-hpa
  namespace: default
spec:
  maxReplicas: 6 # define max replica counts
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loginfunctionality
  targetCPUUtilizationPercentage: 50

