apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:  
  name: loginservicedapr-hpa
  namespace: default
spec:
  maxReplicas: 2 #define max replica counts
  minReplicas: 5 #define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loginservicedapr
  targetCPUUtilizationPercentage: 15
