apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:  
  name: loginservicedapr-hpa
  namespace: default
spec:
  maxReplicas: 11# define max replica counts
  minReplicas: 4# define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loginservicedapr
  targetCPUUtilizationPercentage: 50

#This is a comment