apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: loginfunctionality
  name: loginfunctionality
spec:
  
  selector:
    matchLabels:
      io.kompose.service: loginfunctionality
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: loginfunctionality
    spec:
      imagePullSecrets:
       - name: regcred
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: ' Development'
        - name: RedisCacheConnection
          value: ' 10.0.121.179:6379'
        - name: WebApiBaseUrl
          value: ' http://10.0.157.203:5018/api/'
        name: loginfunctionality       
        image: arck8scr.azurecr.io/loginfunctionality:1562
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"               
        ports:
        - containerPort: 80
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: loginfunctionality
  name: loginfunctionality
spec:
  type: LoadBalancer
  ports:
  - name: "5014"
    port: 5014
    targetPort: 80
  selector:
    io.kompose.service: loginfunctionality
status:
  loadBalancer: {}

