apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:  
  name: productservice-hpa
  namespace: default
spec:
  maxReplicas: 5 #define max replica counts
  minReplicas: 2 #define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productservice
  targetCPUUtilizationPercentage: 15
