apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:  
  name: productservice-hpa
  namespace: default
spec:
  maxReplicas: 3 #define max replica counts
  minReplicas: 3 #define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productservice
  targetCPUUtilizationPercentage: 12
