apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:    
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: rediscache
  name: rediscache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rediscache
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: rediscache
    spec:
      imagePullSecrets:
       - name: regcred
      containers:
      - image: redis:latest
        imagePullPolicy: ""
        name: rediscache
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
